-- Initial schema. Existing installations must follow docs/DATABASES.md before baselining.
create table admin_activity_log (admin_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, ip_address varchar(45), resource_type varchar(50) not null, action varchar(100) not null, resource_id varchar(100), details TEXT, user_agent TEXT, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table admin_permissions (admin_id bigint not null, permission varchar(255)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table admins (is_active bit not null, level integer not null, login_attempts integer not null, auth_version BIGINT DEFAULT 0 not null, created_at datetime(6) not null, created_by bigint, id bigint not null auto_increment, last_login_at datetime(6), locked_until datetime(6), updated_at datetime(6), username varchar(50) not null, salt varchar(64) not null, first_name varchar(100), last_name varchar(100), profile_picture varchar(500), email varchar(255) not null, password_hash varchar(255) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table authentication_error_logs (created_at datetime(6) not null, id bigint not null auto_increment, user_id bigint, http_method varchar(10), role varchar(20), ip_address varchar(45), username varchar(100), attempted_action varchar(200), endpoint varchar(500) not null, error_message TEXT, user_agent TEXT, error_type enum ('ACCESS_DENIED','BAD_REQUEST_400','FORBIDDEN_403','INTERNAL_SERVER_ERROR_500','INVALID_TOKEN','NOT_FOUND_404','UNAUTHORIZED_401') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table password_reset_tokens (attempt_count integer, created_date datetime(6) not null, expiry_date datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, token_preview varchar(32), token_hash varchar(128), requesting_ip varchar(255), role varchar(255) not null, token varchar(255) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table refresh_tokens (is_revoked bit not null, created_at datetime(6) not null, expiry_date datetime(6) not null, id bigint not null auto_increment, last_used_at datetime(6), user_id bigint not null, role varchar(20) not null, token_preview varchar(32), ip_address varchar(45), token_hash varchar(128), device_info varchar(500), token varchar(255) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table sensitive_endpoint_access_logs (email_alert_sent bit, response_status integer, created_at datetime(6) not null, id bigint not null auto_increment, user_id bigint, http_method varchar(10), role varchar(20), ip_address varchar(45), endpoint_category varchar(100), username varchar(100), endpoint varchar(500) not null, description TEXT, user_agent TEXT, severity enum ('CRITICAL','HIGH','LOW','MEDIUM') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table two_factor_credentials (challenge_attempts integer not null, enabled bit not null, admin_id bigint not null, challenge_expires_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, last_code_accepted_at datetime(6), updated_at datetime(6) not null, challenge_hash varchar(64), last_code_hash varchar(64), encrypted_secret varchar(512) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table user_activity_log (success bit not null, created_at datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, role varchar(20) not null, ip_address varchar(45), resource_type varchar(50), action varchar(100) not null, resource_id varchar(100), failure_reason varchar(500), details TEXT, user_agent TEXT, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table users (admin_deactivated bit not null, email_verified bit not null, is_active bit not null, login_attempts integer not null, anonymised_at datetime(6), auth_version BIGINT DEFAULT 0 not null, created_at datetime(6) not null, deactivated_at datetime(6), id bigint not null auto_increment, last_login_at datetime(6), locked_until datetime(6), updated_at datetime(6), phone varchar(20), username varchar(50) not null, salt varchar(64) not null, first_name varchar(100), last_name varchar(100), profile_picture varchar(500), bio TEXT, email varchar(255) not null, password_hash varchar(255) not null, pending_email varchar(255), user_type enum ('APP_USER') not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create table verification_tokens (created_date datetime(6) not null, expiry_date datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, token_preview varchar(32), token_hash varchar(128), role varchar(255) not null, token varchar(255) not null, primary key (id)) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin;
create index idx_admin_activity_admin_id on admin_activity_log (admin_id);
create index idx_admin_activity_action on admin_activity_log (action);
create index idx_admin_activity_resource_type on admin_activity_log (resource_type);
create index idx_admin_activity_created_at on admin_activity_log (created_at);
create index idx_admin_activity_admin_date on admin_activity_log (admin_id, created_at);
create index idx_admin_email on admins (email);
create index idx_admin_username on admins (username);
create index idx_admin_level on admins (level);
create index idx_admin_is_active on admins (is_active);
create index idx_admin_level_active on admins (level, is_active);
create index idx_admin_created_by on admins (created_by);
alter table if exists admins add constraint UKmi8vkhus4xbdbqcac2jm4spvd unique (username);
alter table if exists admins add constraint UK47bvqemyk6vlm0w7crc3opdd4 unique (email);
create index idx_auth_error_type on authentication_error_logs (error_type);
create index idx_auth_error_user_id on authentication_error_logs (user_id);
create index idx_auth_error_role on authentication_error_logs (role);
create index idx_auth_error_created_at on authentication_error_logs (created_at);
create index idx_auth_error_ip_address on authentication_error_logs (ip_address);
create index idx_password_reset_token on password_reset_tokens (token);
create index idx_password_reset_token_hash on password_reset_tokens (token_hash);
create index idx_password_reset_user on password_reset_tokens (user_id, role);
create index idx_password_reset_role on password_reset_tokens (role);
create index idx_password_reset_expiry_date on password_reset_tokens (expiry_date);
create index idx_password_reset_created_date on password_reset_tokens (created_date);
create index idx_password_reset_requesting_ip on password_reset_tokens (requesting_ip);
alter table if exists password_reset_tokens add constraint UKajre85ybxavf1tt4omkrs5p6g unique (token_hash);
alter table if exists password_reset_tokens add constraint UK71lqwbwtklmljk3qlsugr1mig unique (token);
create index idx_refresh_token on refresh_tokens (token);
create index idx_refresh_token_hash on refresh_tokens (token_hash);
create index idx_refresh_user_composite on refresh_tokens (user_id, role);
create index idx_refresh_expiry_date on refresh_tokens (expiry_date);
create index idx_refresh_is_revoked on refresh_tokens (is_revoked);
alter table if exists refresh_tokens add constraint UKo2mlirhldriil2y7krapq4frt unique (token_hash);
alter table if exists refresh_tokens add constraint UKghpmfn23vmxfu3spu3lfg4r2d unique (token);
create index idx_sensitive_access_user_id on sensitive_endpoint_access_logs (user_id);
create index idx_sensitive_access_role on sensitive_endpoint_access_logs (role);
create index idx_sensitive_access_endpoint on sensitive_endpoint_access_logs (endpoint);
create index idx_sensitive_access_created_at on sensitive_endpoint_access_logs (created_at);
create index idx_sensitive_access_ip_address on sensitive_endpoint_access_logs (ip_address);
create index idx_sensitive_access_severity on sensitive_endpoint_access_logs (severity);
create index idx_two_factor_challenge_hash on two_factor_credentials (challenge_hash);
alter table if exists two_factor_credentials add constraint idx_two_factor_admin unique (admin_id);
create index idx_user_activity_user on user_activity_log (user_id, role);
create index idx_user_activity_action on user_activity_log (action);
create index idx_user_activity_created_at on user_activity_log (created_at);
create index idx_user_email on users (email);
create index idx_user_username on users (username);
create index idx_user_is_active on users (is_active);
create index idx_user_email_verified on users (email_verified);
create index idx_user_user_type on users (user_type);
create index idx_user_active_verified on users (is_active, email_verified);
create index idx_user_cleanup_candidates on users (is_active, admin_deactivated, anonymised_at, deactivated_at);
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create index idx_verification_token on verification_tokens (token);
create index idx_verification_token_hash on verification_tokens (token_hash);
create index idx_verification_user on verification_tokens (user_id, role);
create index idx_verification_role on verification_tokens (role);
create index idx_verification_expiry_date on verification_tokens (expiry_date);
create index idx_verification_created_date on verification_tokens (created_date);
alter table if exists verification_tokens add constraint UKclh4tfurdi6ate1t2815l1vn8 unique (token_hash);
alter table if exists verification_tokens add constraint UK6q9nsb665s9f8qajm3j07kd1e unique (token);
alter table if exists admin_activity_log add constraint FKh3qrvwbtw4ax1yfpsgqmexvwj foreign key (admin_id) references admins (id);
alter table if exists admin_permissions add constraint FK7vyuc2dwnyqi0v44ab5n5faca foreign key (admin_id) references admins (id);
