spring.config.activate.on-profile=prod
app.swagger.enabled=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
app.refresh-token.use-cookies=true
app.refresh-token.cookie-secure=true
app.rate-limit.fail-open=false
app.data.init-users=false
server.error.include-message=never
